#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done
bootddev=$(cat /proc/cmdline  | sed  -n  "s#root=\(\/dev\/mmcblk[0-9]\).*#\1#p" )
#printf "fix\n" | parted ---pretend-input-tty ${bootddev} print  >/dev/null 2>&1

cat /etc/version/release_version
# if ! `grep mmc /proc/cmdline >/dev/null` ; then
# 	if `grep mtd5 /proc/mtd >/dev/null`; then
# 		mount -t jffs2 /dev/mtdblock5 /mnt || (flash_erase /dev/mtd5 0 0; mount -t jffs2 /dev/mtdblock5 /mnt)
# 	fi;
# fi

cd /mnt
insmod k_ipcm.ko

insmod k_virt-tty.ko

mkdir /sharefs -p
if `grep mmcblk0p3 /proc/cmdline >/dev/null` ; then
	mount /dev/mmcblk0p4 /sharefs
elif `grep mmcblk1p3 /proc/cmdline >/dev/null` ; then
	mount /dev/mmcblk1p4 /sharefs
fi

./sharefs &
cd -

ifconfig etho up
if [ $? -eq 0 ]; then
    echo "**** Up eth0 interface *****"
    ifconfig eth0 192.168.1.100 netmask 255.255.255.0
    route add default gw 192.168.101.1 eth0
elif [ -f "/etc/wpa_supplicant.conf" ]; then
    echo "**** Up wlan0 interface ****"
    ifconfig wlan0 up
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
    udhcpc -i wlan0 &
fi

